FROM ubuntu:focal

RUN set -eux \
  ; apt-get update \
  ; apt-get upgrade -y \
  ; DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      git build-essential \
      curl ca-certificates \
      ninja-build gettext \
      libtool libtool-bin \
      autoconf automake cmake \
      g++ pkg-config unzip \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
